modLoader="javafml"
loaderVersion="[35,)"
license="Direct"

[[mods]]
modId="dreams"
version="2.1.28"
displayName="Dreams"
credits="Mod Creator: misterrredstone/Jaden LeMieux - Videos: https://www.youtube.com/watch?v=zCZoEOxS4cQ - https://www.youtube.com/watch?v=3ls1meCNgfM, https://www.youtube.com/watch?v=42fLWXy6LbM, Thank you guys!"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dream"
logoFile="logo.png"
authors="Jaden LeMieux/JWMC/JadensWeb/misterrredstone, SwanSpike, MaskedRPM8/MinKun, Dream."
description='''
This is a mod for Minecraft 1.15.2 that adds all things related to the recently blooming YouTuber, Dream!
'''

[[dependencies.dreams]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"




